name: Checkmarx CI/CD Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger Scan
        id: trigger
        env:
          CX_API_KEY: ${{ secrets.CHECKMARX_API_KEY }}
          CX_SERVER: https://<your-checkmarx-server>
          PROJECT_NAME: JuiceShop
        run: |
          echo "Triggering Checkmarx scan..."
          RESPONSE=$(curl -s -X POST "$CX_SERVER/cxrestapi/sast/scans" \
            -H "Authorization: Bearer $CX_API_KEY" \
            -F "projectName=$PROJECT_NAME" \
            -F "source=@./")
          echo "Response from server:"
          echo "$RESPONSE"

          # Extract the scan ID from the response
          SCAN_ID=$(echo $RESPONSE | jq -r '.id')
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
      - name: Wait for Scan Completion
        env:
          CX_API_KEY: ${{ secrets.CHECKMARX_API_KEY }}
          CX_SERVER: https://<your-checkmarx-server>
        run: |
          echo "Polling scan status..."
          STATUS="Queued"
          while [[ "$STATUS" != "Finished" ]]; do
            sleep 15
            STATUS=$(curl -s -X GET "$CX_SERVER/cxrestapi/sast/scans/$SCAN_ID" \
              -H "Authorization: Bearer $CX_API_KEY" | jq -r '.status.name')
            echo "Current scan status: $STATUS"
          done
          echo "Scan completed!"
      - name: Download Scan Report
        env:
          CX_API_KEY: ${{ secrets.CHECKMARX_API_KEY }}
          CX_SERVER: https://<your-checkmarx-server>
        run: >
          echo "Downloading scan report..."

          curl -s -X GET
          "$CX_SERVER/cxrestapi/sast/scans/$SCAN_ID/reports/summary" \
            -H "Authorization: Bearer $CX_API_KEY" \
            -o checkmarx-report.json
          ls -la checkmarx-report.json
      - name: Upload Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: checkmarx-report
          path: checkmarx-report.json
